"""Add CASCADE to foreign keys

Revision ID: 75eaffd91ea5
Revises: a2aae34d69cb
Create Date: 2026-07-05 16:46:14.479623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75eaffd91ea5'
down_revision: Union[str, None] = 'a2aae34d69cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_conversations_user_id_fkey'), 'ai_conversations', type_='foreignkey')
    op.create_foreign_key(None, 'ai_conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('appointments_patient_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_constraint(op.f('appointments_doctor_id_fkey'), 'appointments', type_='foreignkey')
    op.create_foreign_key(None, 'appointments', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('benefits_patient_id_fkey'), 'benefits', type_='foreignkey')
    op.create_foreign_key(None, 'benefits', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('doctors_user_id_fkey'), 'doctors', type_='foreignkey')
    op.drop_constraint(op.f('doctors_hospital_id_fkey'), 'doctors', type_='foreignkey')
    op.create_foreign_key(None, 'doctors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'doctors', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('family_members_patient_id_fkey'), 'family_members', type_='foreignkey')
    op.create_foreign_key(None, 'family_members', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('lab_reports_patient_id_fkey'), 'lab_reports', type_='foreignkey')
    op.create_foreign_key(None, 'lab_reports', 'users', ['patient_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'patient_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_timeline_events_patient_occurred_at'), table_name='timeline_events')
    op.create_index('idx_timeline_events_patient_occurred_at', 'timeline_events', ['patient_id', 'occurred_at'], unique=False, postgresql_ops={'occurred_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timeline_events_patient_occurred_at', table_name='timeline_events', postgresql_ops={'occurred_at': 'DESC'})
    op.create_index(op.f('idx_timeline_events_patient_occurred_at'), 'timeline_events', ['patient_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_constraint(None, 'patient_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('patient_profiles_user_id_fkey'), 'patient_profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'lab_reports', type_='foreignkey')
    op.create_foreign_key(op.f('lab_reports_patient_id_fkey'), 'lab_reports', 'users', ['patient_id'], ['id'])
    op.drop_constraint(None, 'family_members', type_='foreignkey')
    op.create_foreign_key(op.f('family_members_patient_id_fkey'), 'family_members', 'users', ['patient_id'], ['id'])
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.drop_constraint(None, 'doctors', type_='foreignkey')
    op.create_foreign_key(op.f('doctors_hospital_id_fkey'), 'doctors', 'hospitals', ['hospital_id'], ['id'])
    op.create_foreign_key(op.f('doctors_user_id_fkey'), 'doctors', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'benefits', type_='foreignkey')
    op.create_foreign_key(op.f('benefits_patient_id_fkey'), 'benefits', 'users', ['patient_id'], ['id'])
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.create_foreign_key(op.f('appointments_doctor_id_fkey'), 'appointments', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(op.f('appointments_patient_id_fkey'), 'appointments', 'users', ['patient_id'], ['id'])
    op.drop_constraint(None, 'ai_conversations', type_='foreignkey')
    op.create_foreign_key(op.f('ai_conversations_user_id_fkey'), 'ai_conversations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
