"""Add name to Doctor

Revision ID: 7d0f9d0eeacc
Revises: 521a1857197a
Create Date: 2026-07-04 19:53:00.880581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0f9d0eeacc'
down_revision: Union[str, None] = '521a1857197a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('name', sa.String(), server_default='Unknown', nullable=False))
    op.drop_index(op.f('idx_timeline_events_patient_occurred_at'), table_name='timeline_events')
    op.create_index('idx_timeline_events_patient_occurred_at', 'timeline_events', ['patient_id', 'occurred_at'], unique=False, postgresql_ops={'occurred_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timeline_events_patient_occurred_at', table_name='timeline_events', postgresql_ops={'occurred_at': 'DESC'})
    op.create_index(op.f('idx_timeline_events_patient_occurred_at'), 'timeline_events', ['patient_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_column('doctors', 'name')
    # ### end Alembic commands ###
