"""Add rich doctor fields

Revision ID: c6e568f9a89e
Revises: 7d0f9d0eeacc
Create Date: 2026-07-04 20:32:56.054825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e568f9a89e'
down_revision: Union[str, None] = '7d0f9d0eeacc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('rating', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('doctors', sa.Column('experience', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('languages', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('consultation_fee', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('availability', sa.String(), nullable=True))
    op.drop_index(op.f('idx_timeline_events_patient_occurred_at'), table_name='timeline_events')
    op.create_index('idx_timeline_events_patient_occurred_at', 'timeline_events', ['patient_id', 'occurred_at'], unique=False, postgresql_ops={'occurred_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timeline_events_patient_occurred_at', table_name='timeline_events', postgresql_ops={'occurred_at': 'DESC'})
    op.create_index(op.f('idx_timeline_events_patient_occurred_at'), 'timeline_events', ['patient_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_column('doctors', 'availability')
    op.drop_column('doctors', 'consultation_fee')
    op.drop_column('doctors', 'languages')
    op.drop_column('doctors', 'experience')
    op.drop_column('doctors', 'rating')
    # ### end Alembic commands ###
