"""Add role and context payload to AIConversation

Revision ID: e4a689c33ee1
Revises: 75eaffd91ea5
Create Date: 2026-07-05 22:28:46.266800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4a689c33ee1'
down_revision: Union[str, None] = '75eaffd91ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_conversations', sa.Column('role', sa.String(), nullable=True))
    op.add_column('ai_conversations', sa.Column('context_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index(op.f('idx_timeline_events_patient_occurred_at'), table_name='timeline_events')
    op.create_index('idx_timeline_events_patient_occurred_at', 'timeline_events', ['patient_id', 'occurred_at'], unique=False, postgresql_ops={'occurred_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timeline_events_patient_occurred_at', table_name='timeline_events', postgresql_ops={'occurred_at': 'DESC'})
    op.create_index(op.f('idx_timeline_events_patient_occurred_at'), 'timeline_events', ['patient_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.drop_column('ai_conversations', 'context_payload')
    op.drop_column('ai_conversations', 'role')
    # ### end Alembic commands ###
