"""add_emergency_contacts_medical_info_notification_prefs_feedback

Revision ID: fa8da720e45c
Revises: 02d0f9834bc3
Create Date: 2026-07-07 18:57:40.120260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa8da720e45c'
down_revision: Union[str, None] = '02d0f9834bc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('relationship', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='SUBMITTED', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_information',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('conditions', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('allergies', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('chronic_diseases', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('past_surgeries', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('appointment_reminders', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('medication_reminders', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('lab_report_notifications', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('order_updates', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('emergency_alerts', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('email_notifications', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('push_notifications', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('consent_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('hospital_name', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('requested_data', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(), server_default='PENDING', nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_requests_patient_id'), 'consent_requests', ['patient_id'], unique=False)
    op.alter_column('consent_records', 'granted_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('idx_timeline_events_patient_occurred_at'), table_name='timeline_events')
    op.create_index('idx_timeline_events_patient_occurred_at', 'timeline_events', ['patient_id', 'occurred_at'], unique=False, postgresql_ops={'occurred_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_timeline_events_patient_occurred_at', table_name='timeline_events', postgresql_ops={'occurred_at': 'DESC'})
    op.create_index(op.f('idx_timeline_events_patient_occurred_at'), 'timeline_events', ['patient_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.alter_column('consent_records', 'granted_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_consent_requests_patient_id'), table_name='consent_requests')
    op.drop_table('consent_requests')
    op.drop_table('notification_preferences')
    op.drop_table('medical_information')
    op.drop_table('feedback')
    op.drop_table('emergency_contacts')
    # ### end Alembic commands ###
