// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ABHAIdentityResponse
 */
export type AbhaIdentityResponse = {
    /**
     * Abha Number
     */
    abha_number: string;
    /**
     * Abha Address
     */
    abha_address: string;
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Verification Status
     */
    verification_status: string;
    /**
     * Verification Method
     */
    verification_method?: string | null;
    /**
     * Linked At
     */
    linked_at?: string | null;
    /**
     * Is Primary
     */
    is_primary: boolean;
};

/**
 * ABHALinkRequest
 */
export type AbhaLinkRequest = {
    /**
     * Abha Number
     */
    abha_number: string;
    /**
     * Abha Address
     */
    abha_address: string;
};

/**
 * AIChatRequest
 */
export type AiChatRequest = {
    /**
     * Message
     *
     * The user's message to the AI Assistant
     */
    message: string;
    /**
     * Client Role
     *
     * The role context requested by the frontend ('PATIENT' or 'DOCTOR')
     */
    client_role?: string | null;
};

/**
 * AIChatResponse
 */
export type AiChatResponse = {
    /**
     * Answer
     *
     * The AI's response in markdown format
     */
    answer: string;
    /**
     * Sources
     *
     * List of data sources used to answer the query
     */
    sources: Array<string>;
};

/**
 * AIStreamRequest
 */
export type AiStreamRequest = {
    /**
     * Messages
     *
     * Conversation history including the latest message
     */
    messages: Array<ChatMessage>;
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
    /**
     * Context Payload
     */
    context_payload?: {
        [key: string]: unknown;
    } | null;
    /**
     * Client Role
     *
     * The role context requested by the frontend ('PATIENT' or 'DOCTOR')
     */
    client_role?: string | null;
};

/**
 * AppointmentCreate
 */
export type AppointmentCreate = {
    /**
     * Doctor Id
     */
    doctor_id: string;
    /**
     * Date
     */
    date: string;
    /**
     * Time
     */
    time?: string;
    /**
     * Type
     */
    type?: string;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * AppointmentResponse
 */
export type AppointmentResponse = {
    /**
     * Date
     */
    date: string;
    /**
     * Time
     */
    time?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Type
     */
    type: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Doctor Id
     */
    doctor_id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Patient Name
     */
    patient_name?: string | null;
    /**
     * Meet Link
     */
    meet_link?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * BenefitResponse
 */
export type BenefitResponse = {
    /**
     * Type
     */
    type: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Policy Number
     */
    policy_number: string;
    /**
     * Status
     */
    status: string;
    /**
     * Details
     */
    details?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: string;
};

/**
 * ChatMessage
 */
export type ChatMessage = {
    /**
     * Role
     *
     * 'user' or 'model'
     */
    role: string;
    /**
     * Content
     *
     * The message content
     */
    content: string;
};

/**
 * ConsentRequest
 */
export type ConsentRequest = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Doctor Id
     */
    doctor_id: string;
    /**
     * Hospital Id
     */
    hospital_id: string;
    /**
     * Purpose
     */
    purpose: string;
};

/**
 * ConsentResponse
 */
export type ConsentResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Hospital Id
     */
    hospital_id: string;
    /**
     * Doctor Id
     */
    doctor_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Purpose
     */
    purpose: string;
    /**
     * Granted At
     */
    granted_at: string | null;
    /**
     * Revoked At
     */
    revoked_at: string | null;
};

/**
 * ConsultationCompletion
 */
export type ConsultationCompletion = {
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Medications
     */
    medications?: Array<MedicationCreate> | null;
    /**
     * Lab Orders
     */
    lab_orders?: Array<LabOrderCreate> | null;
};

/**
 * ConversationSchema
 */
export type ConversationSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Messages
     */
    messages?: Array<MessageSchema>;
};

/**
 * ConversationUpdate
 */
export type ConversationUpdate = {
    /**
     * Title
     */
    title: string;
};

/**
 * CreateMedicationOrderRequest
 */
export type CreateMedicationOrderRequest = {
    /**
     * Medication Ids
     */
    medication_ids: Array<string>;
    /**
     * Appointment Id
     */
    appointment_id?: string | null;
    /**
     * Consultation Id
     */
    consultation_id?: string | null;
};

/**
 * DoctorAvailabilityResponse
 */
export type DoctorAvailabilityResponse = {
    /**
     * Isodate
     */
    isoDate: string;
    /**
     * Display
     */
    display: string;
    /**
     * Weekday
     */
    weekday: string;
    /**
     * Month
     */
    month: string;
    /**
     * Year
     */
    year: number;
    /**
     * Time
     */
    time: string;
};

/**
 * DoctorResponse
 */
export type DoctorResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Specialty
     */
    specialty: string;
    /**
     * Hospital Id
     */
    hospital_id: string;
    /**
     * License Ref
     */
    license_ref: string;
    /**
     * Image Url
     */
    image_url?: string | null;
    /**
     * Rating
     */
    rating?: number;
    /**
     * Experience
     */
    experience?: string | null;
    /**
     * Languages
     */
    languages?: string | null;
    /**
     * Consultation Fee
     */
    consultation_fee?: string | null;
    /**
     * Availability
     */
    availability?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Hospital Name
     */
    hospital_name?: string | null;
};

/**
 * FamilyMemberCreate
 */
export type FamilyMemberCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Relation Type
     */
    relation_type: string;
    /**
     * Age
     */
    age: number;
    /**
     * Access Level
     */
    access_level: string;
};

/**
 * FamilyMemberResponse
 */
export type FamilyMemberResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Relation Type
     */
    relation_type: string;
    /**
     * Age
     */
    age: number;
    /**
     * Access Level
     */
    access_level: string;
    /**
     * Id
     */
    id: string;
};

/**
 * FamilyMemberUpdate
 */
export type FamilyMemberUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Relation Type
     */
    relation_type?: string | null;
    /**
     * Age
     */
    age?: number | null;
    /**
     * Access Level
     */
    access_level?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HospitalResponse
 */
export type HospitalResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Location
     */
    location: string;
    /**
     * Id
     */
    id: string;
};

/**
 * ImportRecordsRequest
 */
export type ImportRecordsRequest = {
    /**
     * Hospital Id
     */
    hospital_id: string;
    /**
     * Consent Record Id
     */
    consent_record_id?: string | null;
};

/**
 * ImportSessionResponse
 */
export type ImportSessionResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Hospital Id
     */
    hospital_id: string;
    /**
     * Date
     */
    date: string;
    /**
     * Imported Count
     */
    imported_count: number;
};

/**
 * LabOrderCreate
 */
export type LabOrderCreate = {
    /**
     * Test Name
     */
    test_name: string;
    /**
     * Priority
     */
    priority?: string;
    /**
     * Notes
     */
    notes?: string | null;
};

/**
 * LabOrderResponse
 */
export type LabOrderResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Doctor Id
     */
    doctor_id?: string | null;
    /**
     * Appointment Id
     */
    appointment_id?: string | null;
    /**
     * Test Name
     */
    test_name: string;
    /**
     * Priority
     */
    priority: string;
    /**
     * Notes
     */
    notes?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * LabReportCreate
 */
export type LabReportCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Date
     */
    date: string;
    /**
     * Status
     */
    status: string;
    /**
     * Results
     */
    results?: {
        [key: string]: unknown;
    } | null;
    /**
     * Patient Id
     */
    patient_id: string;
};

/**
 * LabReportResponse
 */
export type LabReportResponse = {
    /**
     * Title
     */
    title: string;
    /**
     * Date
     */
    date: string;
    /**
     * Status
     */
    status: string;
    /**
     * Results
     */
    results?: {
        [key: string]: unknown;
    } | null;
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
};

/**
 * LabReportUpdate
 */
export type LabReportUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Date
     */
    date?: string | null;
    /**
     * Status
     */
    status?: string | null;
    /**
     * Results
     */
    results?: {
        [key: string]: unknown;
    } | null;
};

/**
 * MedicationCreate
 */
export type MedicationCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Dosage
     */
    dosage: string;
    /**
     * Frequency
     */
    frequency: string;
    /**
     * Duration
     */
    duration: string;
    /**
     * Instructions
     */
    instructions?: string | null;
};

/**
 * MedicationOrderResponse
 */
export type MedicationOrderResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Doctor Id
     */
    doctor_id?: string | null;
    /**
     * Appointment Id
     */
    appointment_id?: string | null;
    /**
     * Consultation Id
     */
    consultation_id?: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Medication Ids
     */
    medication_ids: Array<string>;
};

/**
 * MedicationResponse
 */
export type MedicationResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Doctor Id
     */
    doctor_id?: string | null;
    /**
     * Appointment Id
     */
    appointment_id?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Dosage
     */
    dosage: string;
    /**
     * Frequency
     */
    frequency: string;
    /**
     * Duration
     */
    duration: string;
    /**
     * Instructions
     */
    instructions?: string | null;
    /**
     * Status
     */
    status: string;
};

/**
 * MessageSchema
 */
export type MessageSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Content
     */
    content: string;
    /**
     * Sources
     */
    sources?: Array<string> | null;
    /**
     * Actions
     */
    actions?: Array<unknown> | null;
    /**
     * Is Error
     */
    is_error?: boolean;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * PatientProfileResponse
 */
export type PatientProfileResponse = {
    /**
     * Demographics
     */
    demographics?: {
        [key: string]: unknown;
    } | null;
    /**
     * Allergies
     */
    allergies?: Array<string>;
    /**
     * Chronic Conditions
     */
    chronic_conditions?: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * PatientProfileUpdate
 */
export type PatientProfileUpdate = {
    /**
     * Demographics
     */
    demographics?: {
        [key: string]: unknown;
    } | null;
    /**
     * Allergies
     */
    allergies?: Array<string> | null;
    /**
     * Chronic Conditions
     */
    chronic_conditions?: Array<string> | null;
};

/**
 * RoleEnum
 */
export type RoleEnum = 'PATIENT' | 'DOCTOR' | 'ADMIN';

/**
 * RoleSwitchRequest
 */
export type RoleSwitchRequest = {
    /**
     * Role
     */
    role: string;
};

/**
 * SyncConversationRequest
 */
export type SyncConversationRequest = {
    /**
     * Id
     */
    id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Messages
     */
    messages: Array<unknown>;
    /**
     * Context Payload
     */
    context_payload?: {
        [key: string]: unknown;
    } | null;
};

/**
 * TimelineAttachmentSchema
 */
export type TimelineAttachmentSchema = {
    /**
     * Id
     */
    id: string;
    /**
     * File Name
     */
    file_name: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Url
     */
    url: string;
    /**
     * File Size
     */
    file_size: number;
    /**
     * Uploaded At
     */
    uploaded_at: string;
};

/**
 * TimelineEventCreate
 */
export type TimelineEventCreate = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Doctor Id
     */
    doctor_id?: string | null;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Type
     */
    type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Source
     */
    source: string;
    /**
     * Confidence
     */
    confidence?: number | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Structured Payload
     */
    structured_payload: {
        [key: string]: unknown;
    };
    /**
     * Metadata Col
     */
    metadata_col?: {
        [key: string]: unknown;
    } | null;
    /**
     * Supersedes Event Id
     */
    supersedes_event_id?: string | null;
};

/**
 * TimelineEventResponse
 */
export type TimelineEventResponse = {
    /**
     * Patient Id
     */
    patient_id: string;
    /**
     * Doctor Id
     */
    doctor_id?: string | null;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Type
     */
    type: string;
    /**
     * Status
     */
    status: string;
    /**
     * Source
     */
    source: string;
    /**
     * Confidence
     */
    confidence?: number | null;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Structured Payload
     */
    structured_payload: {
        [key: string]: unknown;
    };
    /**
     * Metadata Col
     */
    metadata_col?: {
        [key: string]: unknown;
    } | null;
    /**
     * Supersedes Event Id
     */
    supersedes_event_id?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Attachments
     */
    attachments?: Array<TimelineAttachmentSchema>;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Clerk User Id
     */
    clerk_user_id: string;
    role: RoleEnum;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadinessCheckReadyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/ready';
};

export type ReadinessCheckReadyGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LivenessCheckLiveGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/live';
};

export type LivenessCheckLiveGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClerkWebhookApiV1AuthWebhookPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/webhook';
};

export type ClerkWebhookApiV1AuthWebhookPostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type ClerkWebhookApiV1AuthWebhookPostResponse = ClerkWebhookApiV1AuthWebhookPostResponses[keyof ClerkWebhookApiV1AuthWebhookPostResponses];

export type GetCurrentUserInfoApiV1AuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/me';
};

export type GetCurrentUserInfoApiV1AuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type GetCurrentUserInfoApiV1AuthMeGetResponse = GetCurrentUserInfoApiV1AuthMeGetResponses[keyof GetCurrentUserInfoApiV1AuthMeGetResponses];

export type SwitchRoleApiV1AuthSwitchRolePostData = {
    body: RoleSwitchRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/switch-role';
};

export type SwitchRoleApiV1AuthSwitchRolePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SwitchRoleApiV1AuthSwitchRolePostError = SwitchRoleApiV1AuthSwitchRolePostErrors[keyof SwitchRoleApiV1AuthSwitchRolePostErrors];

export type SwitchRoleApiV1AuthSwitchRolePostResponses = {
    /**
     * Successful Response
     */
    200: UserResponse;
};

export type SwitchRoleApiV1AuthSwitchRolePostResponse = SwitchRoleApiV1AuthSwitchRolePostResponses[keyof SwitchRoleApiV1AuthSwitchRolePostResponses];

export type ListTimelineEventsApiV1TimelineGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Type
         */
        type?: string | null;
        /**
         * Tags
         */
        tags?: Array<string> | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor Date
         */
        cursor_date?: string | null;
        /**
         * Cursor Id
         */
        cursor_id?: string | null;
        /**
         * Patient Id
         */
        patient_id?: string | null;
    };
    url: '/api/v1/timeline';
};

export type ListTimelineEventsApiV1TimelineGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTimelineEventsApiV1TimelineGetError = ListTimelineEventsApiV1TimelineGetErrors[keyof ListTimelineEventsApiV1TimelineGetErrors];

export type ListTimelineEventsApiV1TimelineGetResponses = {
    /**
     * Response List Timeline Events Api V1 Timeline Get
     *
     * Successful Response
     */
    200: Array<TimelineEventResponse>;
};

export type ListTimelineEventsApiV1TimelineGetResponse = ListTimelineEventsApiV1TimelineGetResponses[keyof ListTimelineEventsApiV1TimelineGetResponses];

export type CreateTimelineEventApiV1TimelinePostData = {
    body: TimelineEventCreate;
    path?: never;
    query?: never;
    url: '/api/v1/timeline';
};

export type CreateTimelineEventApiV1TimelinePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTimelineEventApiV1TimelinePostError = CreateTimelineEventApiV1TimelinePostErrors[keyof CreateTimelineEventApiV1TimelinePostErrors];

export type CreateTimelineEventApiV1TimelinePostResponses = {
    /**
     * Successful Response
     */
    201: TimelineEventResponse;
};

export type CreateTimelineEventApiV1TimelinePostResponse = CreateTimelineEventApiV1TimelinePostResponses[keyof CreateTimelineEventApiV1TimelinePostResponses];

export type GetTimelineEventApiV1TimelineEventIdGetData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/api/v1/timeline/{event_id}';
};

export type GetTimelineEventApiV1TimelineEventIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetTimelineEventApiV1TimelineEventIdGetError = GetTimelineEventApiV1TimelineEventIdGetErrors[keyof GetTimelineEventApiV1TimelineEventIdGetErrors];

export type GetTimelineEventApiV1TimelineEventIdGetResponses = {
    /**
     * Successful Response
     */
    200: TimelineEventResponse;
};

export type GetTimelineEventApiV1TimelineEventIdGetResponse = GetTimelineEventApiV1TimelineEventIdGetResponses[keyof GetTimelineEventApiV1TimelineEventIdGetResponses];

export type CorrectTimelineEventApiV1TimelineEventIdCorrectPostData = {
    body: TimelineEventCreate;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/api/v1/timeline/{event_id}/correct';
};

export type CorrectTimelineEventApiV1TimelineEventIdCorrectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CorrectTimelineEventApiV1TimelineEventIdCorrectPostError = CorrectTimelineEventApiV1TimelineEventIdCorrectPostErrors[keyof CorrectTimelineEventApiV1TimelineEventIdCorrectPostErrors];

export type CorrectTimelineEventApiV1TimelineEventIdCorrectPostResponses = {
    /**
     * Successful Response
     */
    200: TimelineEventResponse;
};

export type CorrectTimelineEventApiV1TimelineEventIdCorrectPostResponse = CorrectTimelineEventApiV1TimelineEventIdCorrectPostResponses[keyof CorrectTimelineEventApiV1TimelineEventIdCorrectPostResponses];

export type ArchiveTimelineEventApiV1TimelineEventIdArchivePatchData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/api/v1/timeline/{event_id}/archive';
};

export type ArchiveTimelineEventApiV1TimelineEventIdArchivePatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ArchiveTimelineEventApiV1TimelineEventIdArchivePatchError = ArchiveTimelineEventApiV1TimelineEventIdArchivePatchErrors[keyof ArchiveTimelineEventApiV1TimelineEventIdArchivePatchErrors];

export type ArchiveTimelineEventApiV1TimelineEventIdArchivePatchResponses = {
    /**
     * Successful Response
     */
    200: TimelineEventResponse;
};

export type ArchiveTimelineEventApiV1TimelineEventIdArchivePatchResponse = ArchiveTimelineEventApiV1TimelineEventIdArchivePatchResponses[keyof ArchiveTimelineEventApiV1TimelineEventIdArchivePatchResponses];

export type GetAllApiV1AppointmentsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/appointments/';
};

export type GetAllApiV1AppointmentsGetResponses = {
    /**
     * Response Get All Api V1 Appointments  Get
     *
     * Successful Response
     */
    200: Array<AppointmentResponse>;
};

export type GetAllApiV1AppointmentsGetResponse = GetAllApiV1AppointmentsGetResponses[keyof GetAllApiV1AppointmentsGetResponses];

export type CreateAppointmentApiV1AppointmentsPostData = {
    body: AppointmentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/appointments/';
};

export type CreateAppointmentApiV1AppointmentsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAppointmentApiV1AppointmentsPostError = CreateAppointmentApiV1AppointmentsPostErrors[keyof CreateAppointmentApiV1AppointmentsPostErrors];

export type CreateAppointmentApiV1AppointmentsPostResponses = {
    /**
     * Successful Response
     */
    201: AppointmentResponse;
};

export type CreateAppointmentApiV1AppointmentsPostResponse = CreateAppointmentApiV1AppointmentsPostResponses[keyof CreateAppointmentApiV1AppointmentsPostResponses];

export type CompleteConsultationApiV1AppointmentsAppointmentIdCompletePostData = {
    body: ConsultationCompletion;
    path: {
        /**
         * Appointment Id
         */
        appointment_id: string;
    };
    query?: never;
    url: '/api/v1/appointments/{appointment_id}/complete';
};

export type CompleteConsultationApiV1AppointmentsAppointmentIdCompletePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteConsultationApiV1AppointmentsAppointmentIdCompletePostError = CompleteConsultationApiV1AppointmentsAppointmentIdCompletePostErrors[keyof CompleteConsultationApiV1AppointmentsAppointmentIdCompletePostErrors];

export type CompleteConsultationApiV1AppointmentsAppointmentIdCompletePostResponses = {
    /**
     * Successful Response
     */
    200: AppointmentResponse;
};

export type CompleteConsultationApiV1AppointmentsAppointmentIdCompletePostResponse = CompleteConsultationApiV1AppointmentsAppointmentIdCompletePostResponses[keyof CompleteConsultationApiV1AppointmentsAppointmentIdCompletePostResponses];

export type GetConsultationApiV1AppointmentsAppointmentIdConsultationGetData = {
    body?: never;
    path: {
        /**
         * Appointment Id
         */
        appointment_id: string;
    };
    query?: never;
    url: '/api/v1/appointments/{appointment_id}/consultation';
};

export type GetConsultationApiV1AppointmentsAppointmentIdConsultationGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConsultationApiV1AppointmentsAppointmentIdConsultationGetError = GetConsultationApiV1AppointmentsAppointmentIdConsultationGetErrors[keyof GetConsultationApiV1AppointmentsAppointmentIdConsultationGetErrors];

export type GetConsultationApiV1AppointmentsAppointmentIdConsultationGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMyProfileApiV1DoctorsMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/doctors/me';
};

export type GetMyProfileApiV1DoctorsMeGetResponses = {
    /**
     * Successful Response
     */
    200: DoctorResponse;
};

export type GetMyProfileApiV1DoctorsMeGetResponse = GetMyProfileApiV1DoctorsMeGetResponses[keyof GetMyProfileApiV1DoctorsMeGetResponses];

export type GetAllApiV1DoctorsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/doctors/';
};

export type GetAllApiV1DoctorsGetResponses = {
    /**
     * Response Get All Api V1 Doctors  Get
     *
     * Successful Response
     */
    200: Array<DoctorResponse>;
};

export type GetAllApiV1DoctorsGetResponse = GetAllApiV1DoctorsGetResponses[keyof GetAllApiV1DoctorsGetResponses];

export type GetDoctorAvailabilityData = {
    body?: never;
    path: {
        /**
         * Doctor Id
         */
        doctor_id: string;
    };
    query?: never;
    url: '/api/v1/doctors/{doctor_id}/availability';
};

export type GetDoctorAvailabilityErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDoctorAvailabilityError = GetDoctorAvailabilityErrors[keyof GetDoctorAvailabilityErrors];

export type GetDoctorAvailabilityResponses = {
    /**
     * Response Getdoctoravailability
     *
     * Successful Response
     */
    200: Array<DoctorAvailabilityResponse>;
};

export type GetDoctorAvailabilityResponse = GetDoctorAvailabilityResponses[keyof GetDoctorAvailabilityResponses];

export type GetAllApiV1HospitalsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/hospitals/';
};

export type GetAllApiV1HospitalsGetResponses = {
    /**
     * Response Get All Api V1 Hospitals  Get
     *
     * Successful Response
     */
    200: Array<HospitalResponse>;
};

export type GetAllApiV1HospitalsGetResponse = GetAllApiV1HospitalsGetResponses[keyof GetAllApiV1HospitalsGetResponses];

export type GetAllApiV1BenefitsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/benefits/';
};

export type GetAllApiV1BenefitsGetResponses = {
    /**
     * Response Get All Api V1 Benefits  Get
     *
     * Successful Response
     */
    200: Array<BenefitResponse>;
};

export type GetAllApiV1BenefitsGetResponse = GetAllApiV1BenefitsGetResponses[keyof GetAllApiV1BenefitsGetResponses];

export type GetAllApiV1FamilyGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/family/';
};

export type GetAllApiV1FamilyGetResponses = {
    /**
     * Response Get All Api V1 Family  Get
     *
     * Successful Response
     */
    200: Array<FamilyMemberResponse>;
};

export type GetAllApiV1FamilyGetResponse = GetAllApiV1FamilyGetResponses[keyof GetAllApiV1FamilyGetResponses];

export type CreateFamilyMemberApiV1FamilyPostData = {
    body: FamilyMemberCreate;
    path?: never;
    query?: never;
    url: '/api/v1/family/';
};

export type CreateFamilyMemberApiV1FamilyPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateFamilyMemberApiV1FamilyPostError = CreateFamilyMemberApiV1FamilyPostErrors[keyof CreateFamilyMemberApiV1FamilyPostErrors];

export type CreateFamilyMemberApiV1FamilyPostResponses = {
    /**
     * Successful Response
     */
    200: FamilyMemberResponse;
};

export type CreateFamilyMemberApiV1FamilyPostResponse = CreateFamilyMemberApiV1FamilyPostResponses[keyof CreateFamilyMemberApiV1FamilyPostResponses];

export type DeleteFamilyMemberApiV1FamilyMemberIdDeleteData = {
    body?: never;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/family/{member_id}';
};

export type DeleteFamilyMemberApiV1FamilyMemberIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFamilyMemberApiV1FamilyMemberIdDeleteError = DeleteFamilyMemberApiV1FamilyMemberIdDeleteErrors[keyof DeleteFamilyMemberApiV1FamilyMemberIdDeleteErrors];

export type DeleteFamilyMemberApiV1FamilyMemberIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteFamilyMemberApiV1FamilyMemberIdDeleteResponse = DeleteFamilyMemberApiV1FamilyMemberIdDeleteResponses[keyof DeleteFamilyMemberApiV1FamilyMemberIdDeleteResponses];

export type UpdateFamilyMemberApiV1FamilyMemberIdPutData = {
    body: FamilyMemberUpdate;
    path: {
        /**
         * Member Id
         */
        member_id: string;
    };
    query?: never;
    url: '/api/v1/family/{member_id}';
};

export type UpdateFamilyMemberApiV1FamilyMemberIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateFamilyMemberApiV1FamilyMemberIdPutError = UpdateFamilyMemberApiV1FamilyMemberIdPutErrors[keyof UpdateFamilyMemberApiV1FamilyMemberIdPutErrors];

export type UpdateFamilyMemberApiV1FamilyMemberIdPutResponses = {
    /**
     * Successful Response
     */
    200: FamilyMemberResponse;
};

export type UpdateFamilyMemberApiV1FamilyMemberIdPutResponse = UpdateFamilyMemberApiV1FamilyMemberIdPutResponses[keyof UpdateFamilyMemberApiV1FamilyMemberIdPutResponses];

export type GetAllApiV1LabsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/labs/';
};

export type GetAllApiV1LabsGetResponses = {
    /**
     * Response Get All Api V1 Labs  Get
     *
     * Successful Response
     */
    200: Array<LabReportResponse>;
};

export type GetAllApiV1LabsGetResponse = GetAllApiV1LabsGetResponses[keyof GetAllApiV1LabsGetResponses];

export type CreateLabReportApiV1LabsPostData = {
    body: LabReportCreate;
    path?: never;
    query?: never;
    url: '/api/v1/labs/';
};

export type CreateLabReportApiV1LabsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateLabReportApiV1LabsPostError = CreateLabReportApiV1LabsPostErrors[keyof CreateLabReportApiV1LabsPostErrors];

export type CreateLabReportApiV1LabsPostResponses = {
    /**
     * Successful Response
     */
    200: LabReportResponse;
};

export type CreateLabReportApiV1LabsPostResponse = CreateLabReportApiV1LabsPostResponses[keyof CreateLabReportApiV1LabsPostResponses];

export type UpdateLabReportApiV1LabsReportIdPutData = {
    body: LabReportUpdate;
    path: {
        /**
         * Report Id
         */
        report_id: string;
    };
    query?: never;
    url: '/api/v1/labs/{report_id}';
};

export type UpdateLabReportApiV1LabsReportIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateLabReportApiV1LabsReportIdPutError = UpdateLabReportApiV1LabsReportIdPutErrors[keyof UpdateLabReportApiV1LabsReportIdPutErrors];

export type UpdateLabReportApiV1LabsReportIdPutResponses = {
    /**
     * Successful Response
     */
    200: LabReportResponse;
};

export type UpdateLabReportApiV1LabsReportIdPutResponse = UpdateLabReportApiV1LabsReportIdPutResponses[keyof UpdateLabReportApiV1LabsReportIdPutResponses];

export type GetAllApiV1ProfileGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/profile/';
};

export type GetAllApiV1ProfileGetResponses = {
    /**
     * Response Get All Api V1 Profile  Get
     *
     * Successful Response
     */
    200: Array<PatientProfileResponse>;
};

export type GetAllApiV1ProfileGetResponse = GetAllApiV1ProfileGetResponses[keyof GetAllApiV1ProfileGetResponses];

export type GetByUserIdApiV1ProfileUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profile/{user_id}';
};

export type GetByUserIdApiV1ProfileUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetByUserIdApiV1ProfileUserIdGetError = GetByUserIdApiV1ProfileUserIdGetErrors[keyof GetByUserIdApiV1ProfileUserIdGetErrors];

export type GetByUserIdApiV1ProfileUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: PatientProfileResponse;
};

export type GetByUserIdApiV1ProfileUserIdGetResponse = GetByUserIdApiV1ProfileUserIdGetResponses[keyof GetByUserIdApiV1ProfileUserIdGetResponses];

export type UpdateProfileApiV1ProfileUserIdPutData = {
    body: PatientProfileUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/profile/{user_id}';
};

export type UpdateProfileApiV1ProfileUserIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileApiV1ProfileUserIdPutError = UpdateProfileApiV1ProfileUserIdPutErrors[keyof UpdateProfileApiV1ProfileUserIdPutErrors];

export type UpdateProfileApiV1ProfileUserIdPutResponses = {
    /**
     * Successful Response
     */
    200: PatientProfileResponse;
};

export type UpdateProfileApiV1ProfileUserIdPutResponse = UpdateProfileApiV1ProfileUserIdPutResponses[keyof UpdateProfileApiV1ProfileUserIdPutResponses];

export type ChatWithAiApiV1AiChatPostData = {
    body: AiChatRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/chat';
};

export type ChatWithAiApiV1AiChatPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatWithAiApiV1AiChatPostError = ChatWithAiApiV1AiChatPostErrors[keyof ChatWithAiApiV1AiChatPostErrors];

export type ChatWithAiApiV1AiChatPostResponses = {
    /**
     * Successful Response
     */
    200: AiChatResponse;
};

export type ChatWithAiApiV1AiChatPostResponse = ChatWithAiApiV1AiChatPostResponses[keyof ChatWithAiApiV1AiChatPostResponses];

export type ChatWithAiStreamApiV1AiChatStreamPostData = {
    body: AiStreamRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/chat/stream';
};

export type ChatWithAiStreamApiV1AiChatStreamPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChatWithAiStreamApiV1AiChatStreamPostError = ChatWithAiStreamApiV1AiChatStreamPostErrors[keyof ChatWithAiStreamApiV1AiChatStreamPostErrors];

export type ChatWithAiStreamApiV1AiChatStreamPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListConversationsApiV1AiConversationsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/ai/conversations';
};

export type ListConversationsApiV1AiConversationsGetResponses = {
    /**
     * Response List Conversations Api V1 Ai Conversations Get
     *
     * Successful Response
     */
    200: Array<ConversationSchema>;
};

export type ListConversationsApiV1AiConversationsGetResponse = ListConversationsApiV1AiConversationsGetResponses[keyof ListConversationsApiV1AiConversationsGetResponses];

export type DeleteConversationApiV1AiConversationsConversationIdDeleteData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/ai/conversations/{conversation_id}';
};

export type DeleteConversationApiV1AiConversationsConversationIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteConversationApiV1AiConversationsConversationIdDeleteError = DeleteConversationApiV1AiConversationsConversationIdDeleteErrors[keyof DeleteConversationApiV1AiConversationsConversationIdDeleteErrors];

export type DeleteConversationApiV1AiConversationsConversationIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateConversationApiV1AiConversationsConversationIdPatchData = {
    body: ConversationUpdate;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/ai/conversations/{conversation_id}';
};

export type UpdateConversationApiV1AiConversationsConversationIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateConversationApiV1AiConversationsConversationIdPatchError = UpdateConversationApiV1AiConversationsConversationIdPatchErrors[keyof UpdateConversationApiV1AiConversationsConversationIdPatchErrors];

export type UpdateConversationApiV1AiConversationsConversationIdPatchResponses = {
    /**
     * Successful Response
     */
    200: ConversationSchema;
};

export type UpdateConversationApiV1AiConversationsConversationIdPatchResponse = UpdateConversationApiV1AiConversationsConversationIdPatchResponses[keyof UpdateConversationApiV1AiConversationsConversationIdPatchResponses];

export type SyncConversationApiV1AiConversationsSyncPostData = {
    body: SyncConversationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/ai/conversations/sync';
};

export type SyncConversationApiV1AiConversationsSyncPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SyncConversationApiV1AiConversationsSyncPostError = SyncConversationApiV1AiConversationsSyncPostErrors[keyof SyncConversationApiV1AiConversationsSyncPostErrors];

export type SyncConversationApiV1AiConversationsSyncPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetPatientMedicationsApiV1ClinicalPatientsPatientIdMedicationsGetData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/clinical/patients/{patient_id}/medications';
};

export type GetPatientMedicationsApiV1ClinicalPatientsPatientIdMedicationsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPatientMedicationsApiV1ClinicalPatientsPatientIdMedicationsGetError = GetPatientMedicationsApiV1ClinicalPatientsPatientIdMedicationsGetErrors[keyof GetPatientMedicationsApiV1ClinicalPatientsPatientIdMedicationsGetErrors];

export type GetPatientMedicationsApiV1ClinicalPatientsPatientIdMedicationsGetResponses = {
    /**
     * Response Get Patient Medications Api V1 Clinical Patients  Patient Id  Medications Get
     *
     * Successful Response
     */
    200: Array<MedicationResponse>;
};

export type GetPatientMedicationsApiV1ClinicalPatientsPatientIdMedicationsGetResponse = GetPatientMedicationsApiV1ClinicalPatientsPatientIdMedicationsGetResponses[keyof GetPatientMedicationsApiV1ClinicalPatientsPatientIdMedicationsGetResponses];

export type GetPatientMedicationOrdersApiV1ClinicalPatientsPatientIdMedicationOrdersGetData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/clinical/patients/{patient_id}/medication-orders';
};

export type GetPatientMedicationOrdersApiV1ClinicalPatientsPatientIdMedicationOrdersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPatientMedicationOrdersApiV1ClinicalPatientsPatientIdMedicationOrdersGetError = GetPatientMedicationOrdersApiV1ClinicalPatientsPatientIdMedicationOrdersGetErrors[keyof GetPatientMedicationOrdersApiV1ClinicalPatientsPatientIdMedicationOrdersGetErrors];

export type GetPatientMedicationOrdersApiV1ClinicalPatientsPatientIdMedicationOrdersGetResponses = {
    /**
     * Response Get Patient Medication Orders Api V1 Clinical Patients  Patient Id  Medication Orders Get
     *
     * Successful Response
     */
    200: Array<MedicationOrderResponse>;
};

export type GetPatientMedicationOrdersApiV1ClinicalPatientsPatientIdMedicationOrdersGetResponse = GetPatientMedicationOrdersApiV1ClinicalPatientsPatientIdMedicationOrdersGetResponses[keyof GetPatientMedicationOrdersApiV1ClinicalPatientsPatientIdMedicationOrdersGetResponses];

export type CreatePatientMedicationOrderApiV1ClinicalPatientsPatientIdMedicationOrdersPostData = {
    body: CreateMedicationOrderRequest;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/clinical/patients/{patient_id}/medication-orders';
};

export type CreatePatientMedicationOrderApiV1ClinicalPatientsPatientIdMedicationOrdersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePatientMedicationOrderApiV1ClinicalPatientsPatientIdMedicationOrdersPostError = CreatePatientMedicationOrderApiV1ClinicalPatientsPatientIdMedicationOrdersPostErrors[keyof CreatePatientMedicationOrderApiV1ClinicalPatientsPatientIdMedicationOrdersPostErrors];

export type CreatePatientMedicationOrderApiV1ClinicalPatientsPatientIdMedicationOrdersPostResponses = {
    /**
     * Successful Response
     */
    200: MedicationOrderResponse;
};

export type CreatePatientMedicationOrderApiV1ClinicalPatientsPatientIdMedicationOrdersPostResponse = CreatePatientMedicationOrderApiV1ClinicalPatientsPatientIdMedicationOrdersPostResponses[keyof CreatePatientMedicationOrderApiV1ClinicalPatientsPatientIdMedicationOrdersPostResponses];

export type GetPatientLabOrdersApiV1ClinicalPatientsPatientIdLabOrdersGetData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/clinical/patients/{patient_id}/lab-orders';
};

export type GetPatientLabOrdersApiV1ClinicalPatientsPatientIdLabOrdersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPatientLabOrdersApiV1ClinicalPatientsPatientIdLabOrdersGetError = GetPatientLabOrdersApiV1ClinicalPatientsPatientIdLabOrdersGetErrors[keyof GetPatientLabOrdersApiV1ClinicalPatientsPatientIdLabOrdersGetErrors];

export type GetPatientLabOrdersApiV1ClinicalPatientsPatientIdLabOrdersGetResponses = {
    /**
     * Response Get Patient Lab Orders Api V1 Clinical Patients  Patient Id  Lab Orders Get
     *
     * Successful Response
     */
    200: Array<LabOrderResponse>;
};

export type GetPatientLabOrdersApiV1ClinicalPatientsPatientIdLabOrdersGetResponse = GetPatientLabOrdersApiV1ClinicalPatientsPatientIdLabOrdersGetResponses[keyof GetPatientLabOrdersApiV1ClinicalPatientsPatientIdLabOrdersGetResponses];

export type GetClinicalAnalyticsApiV1ClinicalAnalyticsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/clinical/analytics';
};

export type GetClinicalAnalyticsApiV1ClinicalAnalyticsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type LinkAbhaApiV1AbhaLinkPatientIdPostData = {
    body: AbhaLinkRequest;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/abha/link/{patient_id}';
};

export type LinkAbhaApiV1AbhaLinkPatientIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LinkAbhaApiV1AbhaLinkPatientIdPostError = LinkAbhaApiV1AbhaLinkPatientIdPostErrors[keyof LinkAbhaApiV1AbhaLinkPatientIdPostErrors];

export type LinkAbhaApiV1AbhaLinkPatientIdPostResponses = {
    /**
     * Successful Response
     */
    200: AbhaIdentityResponse;
};

export type LinkAbhaApiV1AbhaLinkPatientIdPostResponse = LinkAbhaApiV1AbhaLinkPatientIdPostResponses[keyof LinkAbhaApiV1AbhaLinkPatientIdPostResponses];

export type GetAbhaIdentityApiV1AbhaIdentityPatientIdGetData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/abha/identity/{patient_id}';
};

export type GetAbhaIdentityApiV1AbhaIdentityPatientIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAbhaIdentityApiV1AbhaIdentityPatientIdGetError = GetAbhaIdentityApiV1AbhaIdentityPatientIdGetErrors[keyof GetAbhaIdentityApiV1AbhaIdentityPatientIdGetErrors];

export type GetAbhaIdentityApiV1AbhaIdentityPatientIdGetResponses = {
    /**
     * Successful Response
     */
    200: AbhaIdentityResponse;
};

export type GetAbhaIdentityApiV1AbhaIdentityPatientIdGetResponse = GetAbhaIdentityApiV1AbhaIdentityPatientIdGetResponses[keyof GetAbhaIdentityApiV1AbhaIdentityPatientIdGetResponses];

export type ImportRecordsApiV1AbhaImportPatientIdPostData = {
    body: ImportRecordsRequest;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/abha/import/{patient_id}';
};

export type ImportRecordsApiV1AbhaImportPatientIdPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportRecordsApiV1AbhaImportPatientIdPostError = ImportRecordsApiV1AbhaImportPatientIdPostErrors[keyof ImportRecordsApiV1AbhaImportPatientIdPostErrors];

export type ImportRecordsApiV1AbhaImportPatientIdPostResponses = {
    /**
     * Successful Response
     */
    200: ImportSessionResponse;
};

export type ImportRecordsApiV1AbhaImportPatientIdPostResponse = ImportRecordsApiV1AbhaImportPatientIdPostResponses[keyof ImportRecordsApiV1AbhaImportPatientIdPostResponses];

export type RequestConsentApiV1ConsentRequestPostData = {
    body: ConsentRequest;
    path?: never;
    query?: never;
    url: '/api/v1/consent/request';
};

export type RequestConsentApiV1ConsentRequestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RequestConsentApiV1ConsentRequestPostError = RequestConsentApiV1ConsentRequestPostErrors[keyof RequestConsentApiV1ConsentRequestPostErrors];

export type RequestConsentApiV1ConsentRequestPostResponses = {
    /**
     * Successful Response
     */
    200: ConsentResponse;
};

export type RequestConsentApiV1ConsentRequestPostResponse = RequestConsentApiV1ConsentRequestPostResponses[keyof RequestConsentApiV1ConsentRequestPostResponses];

export type GetPatientConsentsApiV1ConsentPatientPatientIdGetData = {
    body?: never;
    path: {
        /**
         * Patient Id
         */
        patient_id: string;
    };
    query?: never;
    url: '/api/v1/consent/patient/{patient_id}';
};

export type GetPatientConsentsApiV1ConsentPatientPatientIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPatientConsentsApiV1ConsentPatientPatientIdGetError = GetPatientConsentsApiV1ConsentPatientPatientIdGetErrors[keyof GetPatientConsentsApiV1ConsentPatientPatientIdGetErrors];

export type GetPatientConsentsApiV1ConsentPatientPatientIdGetResponses = {
    /**
     * Response Get Patient Consents Api V1 Consent Patient  Patient Id  Get
     *
     * Successful Response
     */
    200: Array<ConsentResponse>;
};

export type GetPatientConsentsApiV1ConsentPatientPatientIdGetResponse = GetPatientConsentsApiV1ConsentPatientPatientIdGetResponses[keyof GetPatientConsentsApiV1ConsentPatientPatientIdGetResponses];

export type ApproveConsentApiV1ConsentConsentIdApprovePostData = {
    body?: never;
    path: {
        /**
         * Consent Id
         */
        consent_id: string;
    };
    query?: never;
    url: '/api/v1/consent/{consent_id}/approve';
};

export type ApproveConsentApiV1ConsentConsentIdApprovePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApproveConsentApiV1ConsentConsentIdApprovePostError = ApproveConsentApiV1ConsentConsentIdApprovePostErrors[keyof ApproveConsentApiV1ConsentConsentIdApprovePostErrors];

export type ApproveConsentApiV1ConsentConsentIdApprovePostResponses = {
    /**
     * Successful Response
     */
    200: ConsentResponse;
};

export type ApproveConsentApiV1ConsentConsentIdApprovePostResponse = ApproveConsentApiV1ConsentConsentIdApprovePostResponses[keyof ApproveConsentApiV1ConsentConsentIdApprovePostResponses];
